return table.freeze({
	[1] = {
		Name = "VIP",
		Description = "Gain access to the VIP training machines!",
		Icon = "VIP",
		Gradient = "Green",
		Price = 339,
	},
	[2] = {
		Name = "x2 Power",
		Description = "Receive a x2 Power multiplier while training!",
		Icon = "x2_Money2",
		Gradient = "Blue",
		Price = 259,
	},
	[4] = {
		Name = "x2 Wins",
		Description = "Receive a x2 Wins multiplier while fighting!",
		Icon = "x2_Wins",
		Gradient = "Pink",
		Price = 249,
	},
	[5] = {
		Name = "x2 Rebirths",
		Description = "Double your rebirths while rebirthing!",
		Icon = "x2_Rebirth",
		Gradient = "Green",
		Price = 299,
	},
	[6] = {
		Name = "+2 Pet Equip",
		Description = "Equip +2 pets at the time!",
		Icon = "plus2_Pet_Equip",
		Gradient = "Blue",
		Price = 49,
	},
	[7] = {
		Name = "+4 Pet Equip",
		Description = "Equip +4 pets at the time!",
		Icon = "plus4_Pet_Equip",
		Gradient = "Yellow",
		Price = 229,
	},
	[8] = {
		Name = "+7 Pet Equip",
		Description = "Equip +7 pets at the time!",
		Icon = "plus7_Pet_Equip",
		Gradient = "Pink",
		Price = 899,
	},
	[9] = {
		Name = "+25 Pet Storage",
		Description = "Store 25 more pets in your inventory!",
		Icon = "plus25_Pet_Storage",
		Gradient = "Green",
		Price = 89,
	},
	[10] = {
		Name = "+50 Pet Storage",
		Description = "Store 50 more pets in your inventory!",
		Icon = "plus50_Pet_Storage",
		Gradient = "Blue",
		Price = 199,
	},
	[11] = {
		Name = "x3 Hatch",
		Description = "Hatch 3 Eggs at the time!",
		Icon = "triple_Hatch",
		Gradient = "Yellow",
		Price = 69,
	},
	[12] = {
		Name = "x8 Hatch",
		Description = "Hatch 8 eggs at the time!",
		Icon = "octuple_Hatch",
		Gradient = "Pink",
		Price = 449,
	},
	-- [13] = {
	--     Name = "Teleport",
	--     Description = "Gives you access to teleport to unlocked areas!",
	--     Icon = "teleport",
	--     Gradient = "Green",
	--     Price = 499
	-- },
	[14] = {
		Name = "Lucky",
		Description = "Receive a x2 luck boost while hatching eggs!",
		Icon = "lucky",
		Gradient = "Blue",
		Price = 199,
	},
	[15] = {
		Name = "Super Lucky",
		Description = "Receive a x3 luck boost while hatching eggs!",
		Icon = "super_Lucky",
		Gradient = "Yellow",
		Price = 549,
	},
	[16] = {
		Name = "Ultra Lucky",
		Description = "Receive a x5 luck boost while hatching eggs!",
		Icon = "ultra_Lucky",
		Gradient = "Pink",
		Price = 999,
	},
})
