return table.freeze({
	[0] = {
		[1] = {
			Fossils = {
				-- Common
				["Branchinecta Fossil"] = {
					Name = "Branchinecta Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Crustacean" },
					MinWeight = 0.05,
					MaxWeight = 0.2,
				},
				["Giant Grasshopper Fossil"] = {
					Name = "Giant Grasshopper Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.1,
					MaxWeight = 0.4,
				},
				["Ancient Termite Nest Fossil"] = {
					Name = "Ancient Termite Nest Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Freshwater Crab Fossil"] = {
					Name = "Freshwater Crab Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Crustacean" },
					MinWeight = 0.1,
					MaxWeight = 0.5,
				},
				["Pleistocene Horse Tooth"] = {
					Name = "Pleistocene Horse Tooth",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Herbivore" },
					MinWeight = 0.2,
					MaxWeight = 0.8,
				},

				-- Uncommon
				["Ornithomimus Leg Bone"] = {
					Name = "Ornithomimus Leg Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Avian" },
					MinWeight = 1.5,
					MaxWeight = 3.5,
				},
				["Struthiomimus Jaw Bone"] = {
					Name = "Struthiomimus Jaw Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Avian" },
					MinWeight = 0.8,
					MaxWeight = 2.0,
				},
				["Tenontosaurus Rib Bone"] = {
					Name = "Tenontosaurus Rib Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Dire Wolf Skull"] = {
					Name = "Dire Wolf Skull",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Carnivore" },
					MinWeight = 3.0,
					MaxWeight = 6.0,
				},
				["Megarachne Fossil"] = {
					Name = "Megarachne Fossil",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Carnivore" },
					MinWeight = 0.5,
					MaxWeight = 1.5,
				},
			},
			Minerals = {
				["Limonite"]  = { Price = 5,  IncomePrice = 1,  Rarity = "Common",   MinWeight = 0.1, MaxWeight = 0.5 },
				["Chert"]     = { Price = 5,  IncomePrice = 1,  Rarity = "Common",   MinWeight = 0.1, MaxWeight = 0.8 },
				["Dolomite"]  = { Price = 10, IncomePrice = 2,  Rarity = "Uncommon", MinWeight = 0.3, MaxWeight = 1.5 },
				["Siderite"]  = { Price = 20, IncomePrice = 5,  Rarity = "Rare",     MinWeight = 0.5, MaxWeight = 2.0 },
				["Septarian"] = { Price = 40, IncomePrice = 10, Rarity = "Epic",     MinWeight = 1.0, MaxWeight = 5.0 },
			},
			Trash = {
				["Bone Dog Toy"] = { Price = 1, IncomePrice = 0, Rarity = "Common", MinWeight = 0.5, MaxWeight = 2.0 },
				["Boots"] = { Price = 1, IncomePrice = 0, Rarity = "Common", MinWeight = 0.5, MaxWeight = 1.0 },
				["Junks"] = { Price = 2, IncomePrice = 0, Rarity = "Common", MinWeight = 1.0, MaxWeight = 3.0 },
				["Rope"] = { Price = 1, IncomePrice = 0, Rarity = "Common", MinWeight = 0.2, MaxWeight = 0.5 },
				["Scraps"] = { Price = 1, IncomePrice = 0, Rarity = "Common", MinWeight = 0.2, MaxWeight = 1.0 },
			},
		},
	},
	
	[1] = {
		[1] = {
			Fossils = {
				-- Common
				["Branchinecta Fossil"] = {
					Name = "Branchinecta Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Crustacean" },
					MinWeight = 0.05,
					MaxWeight = 0.2,
				},
				["Giant Grasshopper Fossil"] = {
					Name = "Giant Grasshopper Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.1,
					MaxWeight = 0.4,
				},
				["Ancient Termite Nest Fossil"] = {
					Name = "Ancient Termite Nest Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Freshwater Crab Fossil"] = {
					Name = "Freshwater Crab Fossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Crustacean" },
					MinWeight = 0.1,
					MaxWeight = 0.5,
				},
				["Pleistocene Horse Tooth"] = {
					Name = "Pleistocene Horse Tooth",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Herbivore" },
					MinWeight = 0.2,
					MaxWeight = 0.8,
				},

				-- Uncommon
				["Ornithomimus Leg Bone"] = {
					Name = "Ornithomimus Leg Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Avian" },
					MinWeight = 1.5,
					MaxWeight = 3.5,
				},
				["Struthiomimus Jaw Bone"] = {
					Name = "Struthiomimus Jaw Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Avian" },
					MinWeight = 0.8,
					MaxWeight = 2.0,
				},
				["Tenontosaurus Rib Bone"] = {
					Name = "Tenontosaurus Rib Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Dire Wolf Skull"] = {
					Name = "Dire Wolf Skull",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Carnivore" },
					MinWeight = 3.0,
					MaxWeight = 6.0,
				},
				["Megarachne Fossil"] = {
					Name = "Megarachne Fossil",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Carnivore" },
					MinWeight = 0.5,
					MaxWeight = 1.5,
				},

				-- Rare
				["Bison Antiquus Horn"] = {
					Name = "Bison Antiquus Horn",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Herbivore" },
					MinWeight = 3.0,
					MaxWeight = 7.0,
				},
				["Varanus Priscus Vertebra"] = {
					Name = "Varanus Priscus Vertebra",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Carnivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Phorusrhacos Beak Fossil"] = {
					Name = "Phorusrhacos Beak Fossil",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Avian" },
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Titanis Leg Bone"] = {
					Name = "Titanis Leg Bone",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Avian" },
					MinWeight = 2.5,
					MaxWeight = 5.5,
				},
				["Argentavis Wing Bone"] = {
					Name = "Argentavis Wing Bone",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Avian" },
					MinWeight = 1.5,
					MaxWeight = 4.0,
				},

				-- Epic
				["Pachycephalosaurus Skull"] = {
					Name = "Pachycephalosaurus Skull",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 8.0,
					MaxWeight = 15.0,
				},
				["Ankylosaurus Tail Bone"] = {
					Name = "Ankylosaurus Tail Bone",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 10.0,
					MaxWeight = 20.0,
				},
				["Megatherium Claw"] = {
					Name = "Megatherium Claw",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Smilodon Saber Tooth"] = {
					Name = "Smilodon Saber Tooth",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Carnivore" },
					MinWeight = 0.5,
					MaxWeight = 1.5,
				},
				["Glyptodon Armor Plate"] = {
					Name = "Glyptodon Armor Plate",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 15.0,
					MaxWeight = 30.0,
				},

				-- Legendary
				["Mammoth Skull"] = {
					Name = "Mammoth Skull",
					Price = 1600,
					IncomePrice = 250,
					Rarity = "Legendary",
					Type = { "Herbivore" },
					MinWeight = 15.0,
					MaxWeight = 30.0,
				},
				["DIatryma Skull"] = {
					Name = "DIatryma Skull",
					Price = 1600,
					IncomePrice = 250,
					Rarity = "Legendary",
					Type = { "Avian" },
					MinWeight = 15.0,
					MaxWeight = 30.0,
				},

				-- Big Skeletons (T-Rex)
				["Tyrannosaurus Rex Skull"] = {
					Name = "Tyrannosaurus Rex Skull",
					IncomePrice = 2000,
					Rarity = "Legendary",
					Type = { "Carnivore" }
				},
				["Tyrannosaurus Rex Body"] = {
					Name = "Tyrannosaurus Rex Body",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" }
				},
				["Tyrannosaurus Rex Left Leg"] = {
					Name = "Tyrannosaurus Rex Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" }
				},
				["Tyrannosaurus Rex Right Leg"] = {
					Name = "Tyrannosaurus Rex Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" }
				},
				["Tyrannosaurus Rex Tail"] = {
					Name = "Tyrannosaurus Rex Tail",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" }
				},

				-- Big Skeletons (Apatosaurus)
				["Apatosaurus Head"] = {
					Name = "Apatosaurus Head",
					IncomePrice = 2000,
					Rarity = "Legendary",
					Type = { "Herbivore" }
				},
				["Apatosaurus Body"] = {
					Name = "Apatosaurus Body",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" }
				},
				["Apatosaurus Tail"] = {
					Name = "Apatosaurus Tail",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" }
				},
				["Apatosaurus Front Leg"] = {
					Name = "Apatosaurus Front Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" }
				},
				["Apatosaurus Back Leg"] = {
					Name = "Apatosaurus Back Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" }
				},
			},

			Minerals = {
				["Limonite"] = {
					Price = 5,
					IncomePrice = 1,
					Rarity = "Common",
					MinWeight = 0.1,
					MaxWeight = 0.5,
				},
				["Chert"] = {
					Price = 5,
					IncomePrice = 1,
					Rarity = "Common",
					MinWeight = 0.1,
					MaxWeight = 0.8,
				},
				["Dolomite"] = {
					Price = 10,
					IncomePrice = 2,
					Rarity = "Uncommon",
					MinWeight = 0.3,
					MaxWeight = 1.5,
				},
				["Siderite"] = {
					Price = 20,
					IncomePrice = 5,
					Rarity = "Rare",
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Septarian"] = {
					Price = 40,
					IncomePrice = 10,
					Rarity = "Epic",
					MinWeight = 1.0,
					MaxWeight = 5.0,
				},
			},

			Trash = {
				["Bone Dog Toy"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Boots"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.5,
					MaxWeight = 1.0,
				},
				["Junks"] = {
					Price = 2,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Rope"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.2,
					MaxWeight = 0.5,
				},
				["Scraps"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.2,
					MaxWeight = 1.0,
				},
			},
		},
	},

	[2] = {
		[1] = {
			Fossils = {
				["AncientStickForest"] = {
					Name = "AncientStickForest",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Plant" },
					MinWeight = 0.1,
					MaxWeight = 1.0,
				},
				["FreshwaterShrimp"] = {
					Name = "FreshwaterShrimp",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Crustacean" },
					MinWeight = 0.05,
					MaxWeight = 0.2,
				},
				["Gecarcinucidae"] = {
					Name = "Gecarcinucidae",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Crustacean" },
					MinWeight = 0.1,
					MaxWeight = 0.5,
				},
				["GiantForestAnt"] = {
					Name = "GiantForestAnt",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.1,
					MaxWeight = 0.4,
				},
				["Pulmonoscorpius"] = {
					Name = "Pulmonoscorpius",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["ArchaeopteryxWingBone"] = {
					Name = "ArchaeopteryxWingBone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Avian" },
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Confuciusornis Wing Bone"] = {
					Name = "Confuciusornis Wing Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Avian" },
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Dryosaurus Rib Bone"] = {
					Name = "Dryosaurus Rib Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Hypsilophodon Leg Bone"] = {
					Name = "Hypsilophodon Leg Bone",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Jungle Scorpion"] = {
					Name = "Jungle Scorpion",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Insecta" },
					MinWeight = 0.5,
					MaxWeight = 1.5,
				},
				["Deinonychus Claw Bone"] = {
					Name = "Deinonychus Claw Bone",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Carnivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Giant Monitor Lizard Skull"] = {
					Name = "Giant Monitor Lizard Skull",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Carnivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Microraptor Skull"] = {
					Name = "Microraptor Skull",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Avian" },
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Psittacosaurus Skull"] = {
					Name = "Psittacosaurus Skull",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Rhamphorhynchus Wing Bone"] = {
					Name = "Rhamphorhynchus Wing Bone",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Avian" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Corythosaurus Crest Bone Textured"] = {
					Name = "Corythosaurus Crest Bone Textured",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 5.0,
					MaxWeight = 15.0,
				},
				["Dilophosaurus Tooth Textured"] = {
					Name = "Dilophosaurus Tooth Textured",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Carnivore" },
					MinWeight = 0.5,
					MaxWeight = 1.5,
				},
				["Early Primate Arm Bone Textured"] = {
					Name = "Early Primate Arm Bone Textured",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Gigantopithecus Jaw Bone Textured"] = {
					Name = "Gigantopithecus Jaw Bone Textured",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Oviraptor Skull Textured"] = {
					Name = "Oviraptor Skull Textured",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Carnivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["TherizinosaurusClaw"] = {
					Name = "TherizinosaurusClaw",
					Price = 1600,
					IncomePrice = 250,
					Rarity = "Legendary",
					Type = { "Herbivore" },
					MinWeight = 15.0,
					MaxWeight = 30.0,
				},
				["TitanoboaVertebrae"] = {
					Name = "TitanoboaVertebrae",
					Price = 1600,
					IncomePrice = 250,
					Rarity = "Legendary",
					Type = { "Carnivore" },
					MinWeight = 15.0,
					MaxWeight = 30.0,
				},
				["Stegosaurus Skull"] = {
					Name = "Stegosaurus Skull",
					IncomePrice = 2000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Stegosaurus Body"] = {
					Name = "Stegosaurus Body",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Stegosaurus Tail"] = {
					Name = "Stegosaurus Tail",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Stegosaurus Front Left Leg"] = {
					Name = "Stegosaurus Front Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Stegosaurus Front Right"] = {
					Name = "Stegosaurus Front Right",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Stegosaurus Rear Left Leg"] = {
					Name = "Stegosaurus Rear Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Stegosaurus Rear Right Leg"] = {
					Name = "Stegosaurus Rear Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Triceratops Skull"] = {
					Name = "Triceratops Skull",
					IncomePrice = 2000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Triceratops Body"] = {
					Name = "Triceratops Body",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Triceratops Tail"] = {
					Name = "Triceratops Tail",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Triceratops Front Left Leg"] = {
					Name = "Triceratops Front Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Triceratops Front Right Leg"] = {
					Name = "Triceratops Front Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Triceratops Rear Left Leg"] = {
					Name = "Triceratops Rear Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
				["Triceratops Rear Right Leg"] = {
					Name = "Triceratops Rear Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Herbivore" },
				},
			},
			Minerals = {
				["Limonite"] = {
					Price = 5,
					IncomePrice = 1,
					Rarity = "Common",
					MinWeight = 0.1,
					MaxWeight = 0.5,
				},
				["Chert"] = {
					Price = 5,
					IncomePrice = 1,
					Rarity = "Common",
					MinWeight = 0.1,
					MaxWeight = 0.8,
				},
				["Dolomite"] = {
					Price = 10,
					IncomePrice = 2,
					Rarity = "Uncommon",
					MinWeight = 0.3,
					MaxWeight = 1.5,
				},
				["Siderite"] = {
					Price = 20,
					IncomePrice = 5,
					Rarity = "Rare",
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Septarian"] = {
					Price = 40,
					IncomePrice = 10,
					Rarity = "Epic",
					MinWeight = 1.0,
					MaxWeight = 5.0,
				},
			},
			Trash = {
				["Bone Dog Toy"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Boots"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.5,
					MaxWeight = 1.0,
				},
				["Junks"] = {
					Price = 2,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Rope"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.2,
					MaxWeight = 0.5,
				},
				["Scraps"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.2,
					MaxWeight = 1.0,
				},
			},
		},
	},

	[3] = {
		[1] = {
			Fossils = {
				["FreshWaterMussel"] = {
					Name = "FreshWaterMussel",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Mollusk" },
					MinWeight = 0.1,
					MaxWeight = 1.0,
				},
				["GarScale"] = {
					Name = "GarScale",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Fish" },
					MinWeight = 0.05,
					MaxWeight = 0.2,
				},
				["GiantWaterBug"] = {
					Name = "GiantWaterBug",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.1,
					MaxWeight = 0.5,
				},
				["NymphDragonfly"] = {
					Name = "NymphDragonfly",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Insecta" },
					MinWeight = 0.1,
					MaxWeight = 0.4,
				},
				["TriopsCancriformisFossil"] = {
					Name = "TriopsCancriformisFossil",
					Price = 100,
					IncomePrice = 10,
					Rarity = "Common",
					Type = { "Crustacean" },
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["AncientRiverCrabClaw"] = {
					Name = "AncientRiverCrabClaw",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Crustacean" },
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["IchthyornisSkull"] = {
					Name = "IchthyornisSkull",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Avian" },
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["LungFishToothPlate"] = {
					Name = "LungFishToothPlate",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Fish" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["SoftShellTurtleShell"] = {
					Name = "SoftShellTurtleShell",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Reptile" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["TiktaalikSkull"] = {
					Name = "TiktaalikSkull",
					Price = 200,
					IncomePrice = 25,
					Rarity = "Uncommon",
					Type = { "Amphibian" },
					MinWeight = 0.5,
					MaxWeight = 1.5,
				},
				["Belemnite Guard (Bullet Fossil)"] = {
					Name = "Belemnite Guard (Bullet Fossil)",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Mollusk" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Early River Dolphin Vertebra"] = {
					Name = "Early River Dolphin Vertebra",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Mammal" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["IguanodonArmBone"] = {
					Name = "IguanodonArmBone",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Herbivore" },
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Mantellisaurus Arm Bone"] = {
					Name = "Mantellisaurus Arm Bone",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Onchopristis Rostrum Tooth"] = {
					Name = "Onchopristis Rostrum Tooth",
					Price = 400,
					IncomePrice = 50,
					Rarity = "Rare",
					Type = { "Fish" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Basilosaurus Rib Bone"] = {
					Name = "Basilosaurus Rib Bone",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Mammal" },
					MinWeight = 5.0,
					MaxWeight = 15.0,
				},
				["Lurdusaurus Leg Bone"] = {
					Name = "Lurdusaurus Leg Bone",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 0.5,
					MaxWeight = 1.5,
				},
				["Ouranosaurus Vertebra1"] = {
					Name = "Ouranosaurus Vertebra1",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Herbivore" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Plesiosaur Neck Bone"] = {
					Name = "Plesiosaur Neck Bone",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Reptile" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Sarcosuchus Tooth"] = {
					Name = "Sarcosuchus Tooth",
					Price = 800,
					IncomePrice = 100,
					Rarity = "Epic",
					Type = { "Reptile" },
					MinWeight = 2.0,
					MaxWeight = 5.0,
				},
				["Deinosuchus Armor Plate"] = {
					Name = "Deinosuchus Armor Plate",
					Price = 1600,
					IncomePrice = 250,
					Rarity = "Legendary",
					Type = { "Reptile" },
					MinWeight = 15.0,
					MaxWeight = 30.0,
				},
				["Stupendemys Shell"] = {
					Name = "Stupendemys Shell",
					Price = 1600,
					IncomePrice = 250,
					Rarity = "Legendary",
					Type = { "Reptile" },
					MinWeight = 15.0,
					MaxWeight = 30.0,
				},
				["Mosasaurus Skull"] = {
					Name = "Mosasaurus Skull",
					IncomePrice = 2000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Mosasaurus Body"] = {
					Name = "Mosasaurus Body",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Mosasaurus Tail"] = {
					Name = "Mosasaurus Tail",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Mosasaurus Front Left Leg"] = {
					Name = "Mosasaurus Front Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Mosasaurus Front Right Leg"] = {
					Name = "Mosasaurus Front Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Mosasaurus Rear Left Leg"] = {
					Name = "Mosasaurus Rear Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Mosasaurus Rear Right Leg"] = {
					Name = "Mosasaurus Rear Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Spinosaurus Skull"] = {
					Name = "Spinosaurus Skull",
					IncomePrice = 2000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Spinosaurus Body"] = {
					Name = "Spinosaurus Body",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Spinosaurus Tail"] = {
					Name = "Spinosaurus Tail",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Spinosaurus Front Left Leg"] = {
					Name = "Spinosaurus Front Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Spinosaurus Front Right Leg"] = {
					Name = "Spinosaurus Front Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Spinosaurus Rear Left Leg"] = {
					Name = "Spinosaurus Rear Left Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
				["Spinosaurus Rear Right Leg"] = {
					Name = "Spinosaurus Rear Right Leg",
					IncomePrice = 1000,
					Rarity = "Legendary",
					Type = { "Carnivore" },
				},
			},
			Minerals = {
				["Limonite"] = {
					Price = 5,
					IncomePrice = 1,
					Rarity = "Common",
					MinWeight = 0.1,
					MaxWeight = 0.5,
				},
				["Chert"] = {
					Price = 5,
					IncomePrice = 1,
					Rarity = "Common",
					MinWeight = 0.1,
					MaxWeight = 0.8,
				},
				["Dolomite"] = {
					Price = 10,
					IncomePrice = 2,
					Rarity = "Uncommon",
					MinWeight = 0.3,
					MaxWeight = 1.5,
				},
				["Siderite"] = {
					Price = 20,
					IncomePrice = 5,
					Rarity = "Rare",
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Septarian"] = {
					Price = 40,
					IncomePrice = 10,
					Rarity = "Epic",
					MinWeight = 1.0,
					MaxWeight = 5.0,
				},
			},
			Trash = {
				["Bone Dog Toy"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.5,
					MaxWeight = 2.0,
				},
				["Boots"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.5,
					MaxWeight = 1.0,
				},
				["Junks"] = {
					Price = 2,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 1.0,
					MaxWeight = 3.0,
				},
				["Rope"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.2,
					MaxWeight = 0.5,
				},
				["Scraps"] = {
					Price = 1,
					IncomePrice = 0,
					Rarity = "Common",
					MinWeight = 0.2,
					MaxWeight = 1.0,
				},
			},
		},
	},

	Mutations = {
		["Gold"] = {
			PriceMultiplier = 5,
			IncomeMultiplier = 5,
		},
		["Diamond"] = {
			PriceMultiplier = 25,
			IncomeMultiplier = 25,
		},
		["Radiation"] = {
			PriceMultiplier = 100,
			IncomeMultiplier = 100,
		},
	},
})
